# Generated by Django 5.1.4 on 2025-02-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description available.')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('thumbnail_1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('thumbnail_2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('thumbnail_3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('thumbnail_4', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.category')),
            ],
        ),
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=7)),
                ('main_image', models.ImageField(upload_to='variant_images/')),
                ('thumbnail_1', models.ImageField(blank=True, null=True, upload_to='variant_images/')),
                ('thumbnail_2', models.ImageField(blank=True, null=True, upload_to='variant_images/')),
                ('thumbnail_3', models.ImageField(blank=True, null=True, upload_to='variant_images/')),
                ('thumbnail_4', models.ImageField(blank=True, null=True, upload_to='variant_images/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text="If different from the product's original price", max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='admin_panel.product')),
            ],
        ),
    ]
