# Generated by Django 5.1.4 on 2025-03-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage', max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('max_usage', models.PositiveIntegerField(default=1, help_text='Maximum number of times the coupon can be used')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Times the coupon has been used')),
            ],
        ),
    ]
