# Generated by Django 5.2 on 2025-04-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_return'),
        ('furniclove_app', '0033_remove_orderitem_is_returned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='admin_note',
        ),
        migrations.AlterField(
            model_name='return',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furniclove_app.orderitem'),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', max_length=20),
        ),
    ]
