# Generated by Django 5.2 on 2025-04-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_remove_return_admin_note_alter_return_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded')], default='Requested', max_length=20),
        ),
    ]
