# Generated by Django 5.1.4 on 2025-02-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='2b05096c2c', max_length=20, unique=True),
        ),
    ]
