# Generated by Django 5.1.4 on 2025-02-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='d5646082ea', max_length=20, unique=True),
        ),
    ]
