# Generated by Django 5.1.4 on 2025-03-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0017_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
