# Generated by Django 5.1.4 on 2025-03-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0021_order_razorpay_payment_id_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
