# Generated by Django 5.1.4 on 2025-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0025_orderitem_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
