# Generated by Django 5.1.4 on 2025-03-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0026_orderitem_return_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='return_requested',
        ),
    ]
