# Generated by Django 5.1.4 on 2025-03-25 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_coupon_min_purchase_amount'),
        ('furniclove_app', '0027_remove_orderitem_return_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.coupon'),
        ),
    ]
