# Generated by Django 5.1.4 on 2025-03-26 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0030_alter_wishlist_unique_together_wishlist_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
