# Generated by Django 5.2 on 2025-04-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0032_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='returned',
        ),
    ]
