# Generated by Django 5.2 on 2025-05-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0036_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
