# Generated by Django 5.2 on 2025-06-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0037_orderitem_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_charge',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
