# Generated by Django 5.2 on 2025-06-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniclove_app', '0039_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
